In [1]:
gold = ["Hello"]

In [2]:
type(gold)

list

In [5]:
import torch
A = torch.randn(5,5)
print(A)
indexes = torch.argmax(A,dim=1)
print(indexes)

tensor([[ 0.3172,  1.3184,  0.7532,  1.3983, -0.0528],
        [ 0.6171, -0.1718, -0.7258, -0.4337, -1.8280],
        [-0.1450, -0.0343, -1.0849, -1.9390, -0.9128],
        [-0.6625,  1.1694,  0.8957, -1.7908,  0.8997],
        [-0.3444, -0.8088,  1.7349,  0.3875,  1.4911]])
tensor([3, 0, 1, 1, 2])


In [7]:
A[indexes]

tensor([[-0.6625,  1.1694,  0.8957, -1.7908,  0.8997],
        [ 0.3172,  1.3184,  0.7532,  1.3983, -0.0528],
        [ 0.6171, -0.1718, -0.7258, -0.4337, -1.8280],
        [ 0.6171, -0.1718, -0.7258, -0.4337, -1.8280],
        [-0.1450, -0.0343, -1.0849, -1.9390, -0.9128]])

In [9]:
B = torch.randn(5)
B

tensor([-0.9988, -0.5318, -1.3841,  1.6433, -0.2941])

In [12]:
A[[0,0],[1,1]]

tensor([1.3184, 1.3184])

In [13]:
B.numpy()

array([-0.9987995 , -0.53177553, -1.3840991 ,  1.6433138 , -0.29411176],
      dtype=float32)

In [6]:
import numpy as np

In [15]:
targets =[0,2,4]
A = [[0,1,2,3,4],
     [1,5,2,4,3],
     [4,5,1,2,3]]

agg_scores_sub = [1 if A[i][0] == targets[i] else 0 for i in range(len(A))]

In [16]:
agg_scores_sub

[1, 0, 1]

In [20]:
scores = np.random.rand(20000,5)*(-1)
scores

array([[-0.46174113, -0.43215481, -0.5271436 , -0.19536413, -0.59523973],
       [-0.835877  , -0.57362481, -0.77541399, -0.59251377, -0.63999592],
       [-0.60123602, -0.51882045, -0.67241142, -0.57793889, -0.4413286 ],
       ...,
       [-0.65115807, -0.27039428, -0.46680561, -0.58290139, -0.39362022],
       [-0.31676811, -0.52288601, -0.76192637, -0.98930498, -0.82150723],
       [-0.30511314, -0.83488515, -0.52080337, -0.76221204, -0.04844705]])

In [31]:
c = 1
stored_scores = []
agg_stored_scores_sub_sub = []
agg_stored_scores_sub = []
agg_stored_scores = []
print_when = [1,3,5,10,50,100,500,1000]
for k in range(10000):
    stored_scores.append(scores[k])
    if c in print_when:
        for i in range(5):
            agg_stored_scores_sub_sub.append(sum([s[i] for s in stored_scores])/c)
        agg_stored_scores_sub.append(agg_stored_scores_sub_sub)
        agg_stored_scores_sub_sub = []
    if c == 1000:
        agg_stored_scores.append(agg_stored_scores_sub)
        agg_stored_scores_sub = []
        stored_scores = []
        c = 0
    c+=1

In [32]:
agg_stored_scores

[[[-0.46174112943271306,
   -0.43215480929024985,
   -0.527143598963762,
   -0.1953641285023363,
   -0.595239733629185],
  [-0.6329513841218192,
   -0.5082000242683512,
   -0.6583230021090074,
   -0.455272263997123,
   -0.5588547519879549],
  [-0.7016634298102342,
   -0.5263627701480562,
   -0.6118632521292663,
   -0.5237274484414731,
   -0.4318708275136296],
  [-0.5105952065436096,
   -0.4575490603950585,
   -0.5756881714045889,
   -0.5407273531351942,
   -0.5402626889302712],
  [-0.5167221277899295,
   -0.4767276771191352,
   -0.4763424916741513,
   -0.4748973656440845,
   -0.5142026527927819],
  [-0.4910319816241519,
   -0.5089573401053885,
   -0.5033725470265856,
   -0.5109090874578406,
   -0.5449431076107212],
  [-0.505012430396002,
   -0.5017051128844012,
   -0.5067660748360795,
   -0.5113571179613811,
   -0.5018823984646407],
  [-0.48852206832575934,
   -0.5012187218383872,
   -0.498215200293936,
   -0.4900928707658567,
   -0.497779250512689]],
 [[-0.47087869565703455,
   -0.296

In [37]:
for i in range(len(agg_stored_scores)):
    print([np.array(agg_stored_scores[i][j]).argmax() for j in range(len(print_when))])

[3, 3, 4, 1, 3, 0, 1, 0]
[2, 3, 3, 3, 2, 2, 2, 2]
[1, 0, 0, 0, 3, 2, 3, 3]
[4, 3, 1, 2, 0, 0, 0, 0]
[4, 4, 4, 4, 4, 3, 3, 3]
[0, 2, 2, 0, 0, 4, 4, 3]
[4, 3, 3, 1, 1, 1, 0, 4]
[3, 1, 1, 3, 0, 1, 4, 4]
[2, 2, 2, 2, 2, 2, 2, 2]
[4, 0, 2, 4, 1, 3, 2, 2]


In [39]:
from rank_bm25 import BM25Okapi

In [31]:
from tqdm.notebook import tqdm

In [42]:
import pandas as pd
df = pd.read_csv("/scratch/s190619/Data_etc/ColBERT/training_sets/MedQA_textbooks_split_triples.tsv", sep="\t",header=None,encoding="utf-8")

In [25]:
#df.drop("Unnamed: 0",axis=1).to_csv("/scratch/s190619/Data_etc/ColBERT/training_sets/FZ_corpus_split_triples.tsv", sep="\t", index=False,header=False)
df.shape

(40070, 4)

In [43]:
df.head()

0  \
0  a pulmonary autopsy specimen from a 58-year-ol...   
1  a pulmonary autopsy specimen from a 58-year-ol...   
2  a pulmonary autopsy specimen from a 58-year-ol...   
3  a pulmonary autopsy specimen from a 58-year-ol...   
4  a pulmonary autopsy specimen from a 58-year-ol...   

                                                   1  \
0  the anticoagulant effect of lmwhs may be parti...   
1  the longitudinal assessment of bariatric surge...   
2  a randomized controlled trial involving 246 lo...   
3  makary et al studied 594 older patients presen...   
4  with the clini-cal history and physical examin...   

                                                   2  
0  essential tremor may cause difficulty in diagn...  
1  gut-associated lymphoid tissues (galt)   lymph...  
2  an autoimmune disorder caused by antibodies di...  
3  baerwald ar, walker ra, pierson ra. growth rat...  
4  few trials have evaluated exercise speciically...

In [37]:
for i in tqdm(range(df.shape[0])):
    if "\t" in df2.iloc[i][3]:
        print(i)

  0%|          | 0/40070 [00:00<?, ?it/s]

In [35]:

df2 = df.copy()
for j in [1,2,3]:
    tmp = []
    for i in tqdm(range(df.shape[0])):
        tmp.append(df.iloc[i][j].replace("\t"," "))
    df2[j] = tmp

  0%|          | 0/40070 [00:00<?, ?it/s]

  0%|          | 0/40070 [00:00<?, ?it/s]

  0%|          | 0/40070 [00:00<?, ?it/s]

In [29]:
i

0

In [41]:
df2.drop(0).drop(0,axis=1).to_csv("/scratch/s190619/Data_etc/ColBERT/training_sets/MedQA_textbooks_split_triples.tsv", sep="\t", header=False,index=False)

In [45]:
1542*30

46260

In [3]:
import pandas as pd
df = pd.read_csv("/scratch/s190619/Data_etc/ColBERT/training_sets/FZ_corpus_split_triples_scrambled.tsv",sep="\t",header=None)

In [4]:
df.shape

(46293, 3)